"""remove stock transaction table

Revision ID: 1bebd86b652e
Revises: 0b480c60e5c0
Create Date: 2019-12-21 11:37:01.941372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bebd86b652e'
down_revision = '0b480c60e5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=60), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('price_per_share', sa.FLOAT(), nullable=True),
    sa.Column('transaction_fee', sa.FLOAT(), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=60), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
