"""add json to paycheck model

Revision ID: 2a0fdebecc96
Revises: 2f26910fc44c
Create Date: 2018-12-02 19:44:30.091306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0fdebecc96'
down_revision = '2f26910fc44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paycheck', sa.Column('properties', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paycheck', 'properties')
    # ### end Alembic commands ###
