"""stock table

Revision ID: 2f26910fc44c
Revises: 46eb887b7d62
Create Date: 2018-09-22 20:30:44.197732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f26910fc44c'
down_revision = '46eb887b7d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('symbol', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.Column('transaction_fee', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transaction')
    # ### end Alembic commands ###
