"""add properties to transactions

Revision ID: 4abad7625cb3
Revises: e7103d35cbdd
Create Date: 2018-12-23 16:46:38.474294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abad7625cb3'
down_revision = 'e7103d35cbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('properties', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'properties')
    # ### end Alembic commands ###
