"""remove stock transactions

Revision ID: 7da9c1e8fc0d
Revises: f323aa9aa7a2
Create Date: 2019-11-24 21:43:58.880664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7da9c1e8fc0d'
down_revision = 'f323aa9aa7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transaction')
    op.drop_column('account', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_table('stock_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('symbol', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('price_per_share', mysql.FLOAT(), nullable=True),
    sa.Column('transaction_fee', mysql.FLOAT(), nullable=True),
    sa.Column('transaction_type', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='stock_transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
