"""remove file format

Revision ID: 8d1dba812cef
Revises: 5b27c108546b
Create Date: 2019-12-21 18:41:06.018350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1dba812cef'
down_revision = '5b27c108546b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_format')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('transaction_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_level', sa.BOOLEAN(), nullable=True))

    op.create_table('file_format',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('header_rows', sa.INTEGER(), nullable=True),
    sa.Column('num_columns', sa.INTEGER(), nullable=True),
    sa.Column('date_column', sa.INTEGER(), nullable=True),
    sa.Column('date_format', sa.VARCHAR(length=60), nullable=True),
    sa.Column('description_column', sa.INTEGER(), nullable=True),
    sa.Column('amount_column', sa.INTEGER(), nullable=True),
    sa.Column('category_column', sa.INTEGER(), nullable=True),
    sa.Column('account_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
