"""add category to accounts

Revision ID: a4294c9103c1
Revises: 2a0fdebecc96
Create Date: 2018-12-15 15:41:55.011379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4294c9103c1'
down_revision = '2a0fdebecc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'category', ['category_id'], ['id'])
    op.add_column('category', sa.Column('type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'type')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'category_id')
    # ### end Alembic commands ###
