"""add type to category table

Revision ID: b3e641d7c3de
Revises: 4abad7625cb3
Create Date: 2019-02-14 21:04:56.639162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e641d7c3de'
down_revision = '4abad7625cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    # ### end Alembic commands ###
