"""add category to account

Revision ID: e7103d35cbdd
Revises: 2a0fdebecc96
Create Date: 2018-12-17 21:00:48.177273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7103d35cbdd'
down_revision = '2a0fdebecc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'category_id')
    # ### end Alembic commands ###
